name: Run Test

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL}}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        working-directory: server
        run: npm install

      - name: Run test
        working-directory: server
        run: npm test
